spring.application.name=mantra-api

mantra.ai.url=https://cardstock-resolute-cataract.ngrok-free.dev/api/generate

spring.datasource.url=jdbc:h2:file:./data/mantra
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
